export { blobToDataUrl } from './blob-to-data-url'
export { blobToText } from './blob-to-text'
export * from './make-dom-static'
export { setCharsetDeclaration } from './set-charset-declaration'
export { setContentSecurityPolicy } from './set-content-security-policy'
export { setMementoTags } from './set-memento-tags'
export { setLinkTarget } from './set-link-target'
